[tool.pytest.ini_options]
minversion = "6.0"
xfail_strict = true
addopts = [
  "-v",
  "--doctest-modules",
  "--ignore=pymc_experimental/model_builder.py"
]

filterwarnings =[
  "error",
  "ignore::UserWarning:arviz.data.inference_data",
  'ignore:.*(\b(pkg_resources\.declare_namespace|np\.bool8)\b).*:DeprecationWarning',
  "ignore::DeprecationWarning:.*numpy.core.fromnumeric*",
  "ignore::DeprecationWarning:.*numpy.core.numerictypes*"
]

[tool.black]
line-length = 100

[tool.coverage.report]
exclude_lines = [
  "pragma: nocover",
  "raise NotImplementedError",
  "if TYPE_CHECKING:",
]

[tool.isort]
profile = "black"
# lines_between_types = 1

[tool.nbqa.mutate]
isort = 1
black = 1
pyupgrade = 1
